// examples/react-app/src/components/stoplightProject.tsx
import '@stoplight/elements/styles/elements.scss';

import { StoplightProject } from '@stoplight/elements';
import React from 'react';

export const StoplightProjectDocs: React.FC = () => {
  return (
    <div>
      <StoplightProject
        basePath="stoplightProject"
        workspace="https://elements.stoplight.io"
        project="studio-demo"
      ></StoplightProject>
    </div>
  );
};

// examples/angular/src/app/stoplight-project/stoplight-project.component.ts
import { Component } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-docs',
  templateUrl: './stoplight-project.component.html',
})
export class StoplightProjectComponent {
  workspaceSlug = 'elements';
  projectSlug = 'studio-demo';
  basePath = environment.basePath ? `${environment.basePath}/stoplight-project` : 'stoplight-project';
}

<div class="docs">
  <elements-stoplight-project
    [workspaceSlug]="workspaceSlug"
    [projectSlug]="projectSlug"
    [basePath]="basePath"
  ></elements-stoplight-project>
</div>
