// examples/angular/src/app/api/api.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-api',
  templateUrl: './api.component.html',
})
export class ApiComponent {
  descriptionUrl = 'https://raw.githubusercontent.com/stoplightio/studio-demo/master/reference/todos/openapi.v1.json';
}

<div class="docs">
  <stoplight-api
    apidescriptionurl="https://raw.githubusercontent.com/stoplightio/studio-demo/master/reference/todos/openapi.v1.json"
    basePath="oas-docs"
  ></stoplight-api>
</div>

// examples/react-cra/src/components/API.tsx
import '@stoplight/elements/styles/elements.scss';

import { API } from '@stoplight/elements';
import React from 'react';

export const StoplightAPI: React.FC = () => {
  return (
    <div className="stoplight-container">
      <API
        basePath="stoplight-api"
        apiDescriptionUrl="https://raw.githubusercontent.com/stoplightio/studio-demo/master/reference/todos/openapi.v1.json"
      ></API>
    </div>
  );
};
