// examples/angular/src/app/stoplight-project/stoplight-project.component.ts
import { Component } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-docs',
  templateUrl: './stoplight-project.component.html',
})
export class StoplightProjectComponent {
  projectId = 'cHJqOjY';
  platformUrl = 'https://x-6195.stoplight-dev.com';
  basePath = environment.basePath ? `${environment.basePath}/stoplight-project` : 'stoplight-project';
}

<div class="docs">
  <elements-stoplight-project
    [platformUrl]="platformUrl"
    [projectId]="projectId"
    [basePath]="basePath"
  ></elements-stoplight-project>
</div>

// examples/react-cra/src/components/StoplightProject.tsx
import '@stoplight/elements/styles/elements.scss';

import { StoplightProject } from '@stoplight/elements-dev-portal';
import React from 'react';

export const StoplightProjectDocs: React.FC = () => {
  return (
    <StoplightProject basePath="stoplight-project" platformUrl="https://x-6195.stoplight-dev.com" projectId="cHJqOjY" />
  );
};
