// examples/react-app/src/components/API.tsx
import React from 'react';
import { API } from '@stoplight/elements'
import '@stoplight/elements/styles/elements.scss'

function stoplightAPI() {
  return (
    <div>
      <API apiDescriptionUrl="https://raw.githubusercontent.com/stoplightio/studio-demo/master/reference/todos/openapi.v1.json"></API>
    </div>
  );
}

export default stoplightAPI;

// examples/angular/src/app/api/api.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-api',
  templateUrl: './api.component.html',
})
export class ApiComponent {
  constructor() {}
}

<div class="docs">
  <stoplight-api
    apidescriptionurl="https://raw.githubusercontent.com/stoplightio/studio-demo/master/reference/todos/openapi.v1.json"
  ></stoplight-api>
</div>
